name: Sync with emdsa2/-mod

on:
    workflow_dispatch:
    # schedule:
    #     - cron: "0 */6 * * *" # 每 6 小时执行一次同步

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v2
            - name: Fetch
              run: git fetch https://github.com/emdsa2/-mod.git
            - name: Merge
              run: git merge https://github.com/emdsa2/-mod.git --no-edit
            - name: Push changes to fork
              run: git push
