name: Sync with emdsa2/-mod

on:
    workflow_dispatch:
    # schedule:
    #     - cron: "0 */6 * * *" # 每 6 小时执行一次同步

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v2
            - name: Fetch https://github.com/emdsa2/-mod.git changes
              run: git fetch emdsa2/-mod
            - name: Merge https://github.com/emdsa2/-mod.git changes
              run: git merge emdsa2/-mod/main --no-edit
            - name: Push changes to fork
              run: git push
